import { useState, useEffect } from 'react';
import { MapContainer, TileLayer, GeoJSON } from 'react-leaflet';
import L from 'leaflet';
import 'leaflet/dist/leaflet.css';

// --- NEW: COLOR MAPPING ---
// These map exactly to the categories generated by your Python ingest script
const CATEGORY_COLORS = {
  'Armed Conflict / Violence': '#ef4444', // Red
  'Protest / Unrest': '#f97316',          // Orange
  'Coercion / Force Posture': '#eab308',  // Yellow
  'Diplomatic Tension': '#3b82f6',        // Blue
  'Other': '#9ca3af'                      // Gray
};

function App() {
  // --- STATE MANAGEMENT ---
  const [geoData, setGeoData] = useState(null);
  const [uniqueDates, setUniqueDates] = useState([]);
  const [selectedDateIndex, setSelectedDateIndex] = useState(0);
  
  const [uniqueCategories, setUniqueCategories] = useState([]);
  const [activeCategories, setActiveCategories] = useState([]);

  // --- DATA FETCHING ---
  useEffect(() => {
    fetch('http://localhost:8000/api/events')
      .then(response => response.json())
      .then(data => {
        const dates = [...new Set(data.features.map(f => f.properties.date))].sort();
        setUniqueDates(dates);
        setSelectedDateIndex(dates.length - 1);
        
        const categories = [...new Set(data.features.map(f => f.properties.category))].sort();
        setUniqueCategories(categories);
        setActiveCategories(categories); 
        
        setGeoData(data);
      })
      .catch(error => console.error('Error fetching data:', error));
  }, []);

  // --- MAP STYLING ---
  const pointToLayer = (feature, latlng) => {
    // NEW: Grab the color based on the category, default to white if unknown
    const markerColor = CATEGORY_COLORS[feature.properties.category] || "#ffffff";
    
    return L.circleMarker(latlng, {
      radius: 6,
      fillColor: markerColor,
      color: "#000",
      weight: 1,
      opacity: 1,
      fillOpacity: 0.8
    });
  };

  const onEachFeature = (feature, layer) => {
    const props = feature.properties;
    layer.bindPopup(`
      <strong>${props.category}</strong><br/>
      Date: ${props.date}<br/>
      Severity: ${props.severity}<br/>
      <a href="${props.source}" target="_blank" style="color: #66b3ff;">Read Source</a>
    `);
  };

  // --- INTERACTION LOGIC ---
  const handleCategoryToggle = (category) => {
    setActiveCategories(prev => 
      prev.includes(category) 
        ? prev.filter(c => c !== category) 
        : [...prev, category]              
    );
  };

  // --- DATA FILTERING ---
  const activeDate = uniqueDates[selectedDateIndex];
  
  const filteredData = geoData ? {
    ...geoData,
    features: geoData.features.filter(f => 
      f.properties.date === activeDate && 
      activeCategories.includes(f.properties.category)
    )
  } : null;

  // --- RENDER ---
  return (
    <div style={{ position: 'relative', height: '100vh', width: '100vw' }}>
      
      {/* THE FLOATING CATEGORY FILTER UI */}
      <div style={{
        position: 'absolute',
        top: '20px',
        right: '20px',
        zIndex: 1000,
        backgroundColor: 'rgba(45, 45, 45, 0.9)',
        padding: '15px',
        borderRadius: '8px',
        color: 'white',
        boxShadow: '0 4px 6px rgba(0,0,0,0.5)',
        minWidth: '220px'
      }}>
        <h4 style={{ margin: '0 0 15px 0', borderBottom: '1px solid #555', paddingBottom: '8px' }}>Filters</h4>
        {uniqueCategories.map(cat => (
          <div key={cat} style={{ marginBottom: '10px' }}>
            <label style={{ cursor: 'pointer', display: 'flex', alignItems: 'center' }}>
              <input 
                type="checkbox" 
                checked={activeCategories.includes(cat)}
                onChange={() => handleCategoryToggle(cat)}
                style={{ marginRight: '10px', cursor: 'pointer' }}
              />
              
              {/* NEW: Colored indicator dot for the menu */}
              <span style={{
                display: 'inline-block',
                width: '12px',
                height: '12px',
                backgroundColor: CATEGORY_COLORS[cat] || '#ffffff',
                borderRadius: '50%',
                marginRight: '8px',
                border: '1px solid #000'
              }}></span>
              
              <span style={{ fontSize: '14px' }}>{cat}</span>
            </label>
          </div>
        ))}
      </div>

      {/* THE FLOATING TIMELINE UI */}
      <div style={{
        position: 'absolute',
        bottom: '30px',
        left: '50%',
        transform: 'translateX(-50%)',
        zIndex: 1000,
        backgroundColor: 'rgba(45, 45, 45, 0.9)',
        padding: '15px 30px',
        borderRadius: '8px',
        color: 'white',
        boxShadow: '0 4px 6px rgba(0,0,0,0.5)',
        width: '300px',
        textAlign: 'center'
      }}>
        <h4 style={{ margin: '0 0 10px 0', fontFamily: 'sans-serif' }}>Event Timeline</h4>
        <p style={{ margin: '0 0 10px 0', fontSize: '14px', color: '#ff4444', fontWeight: 'bold' }}>
          Showing events for: {activeDate || 'Loading...'}
        </p>
        
        <input 
          type="range" 
          min="0" 
          max={Math.max(0, uniqueDates.length - 1)} 
          value={selectedDateIndex} 
          onChange={(e) => setSelectedDateIndex(Number(e.target.value))}
          style={{ width: '100%', cursor: 'pointer' }}
          disabled={uniqueDates.length === 0}
        />
      </div>

      {/* THE MAP */}
      <MapContainer center={[20, 0]} zoom={2} style={{ height: '100%', width: '100%' }}>
        <TileLayer
          url="https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png"
          attribution='&copy; <a href="https://carto.com/">CARTO</a>'
        />
        
        {filteredData && filteredData.features.length > 0 && (
          <GeoJSON 
            key={`geojson-${activeDate}-${activeCategories.length}`} 
            data={filteredData} 
            pointToLayer={pointToLayer} 
            onEachFeature={onEachFeature} 
          />
        )}
      </MapContainer>
    </div>
  );
}

export default App;
